---
name: Release Patch
on: [workflow_dispatch]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - uses: cliffano/release-action@v1.3.0
        with:
          release_type: 'patch'
          github_token: ${{ secrets.STUDIO_GITHUB_TOKEN }}
